services:
  api-vuln:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
  api-hardened:
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
  detector:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
  alerts-api:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
